services:
  - type: web
    name: stealth-crawler-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python start.py
    autoDeploy: true
    envVars:
      - key: PYTHONPATH
        value: .
      - key: PORT
        value: 10000