services:
  - type: web
    name: stealth-crawler-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: PYTHONPATH
        value: .
      - key: ENVIRONMENT
        value: production